### ISSUE TITLE
Icon Issues

### ISSUE THREAD

**Issue by drew0036** [drew0036/just-your-type#2]
![Screen Shot 2020-03-08 at 8 25 31 PM](https://user-images.githubusercontent.com/55107709/76174034-03274b80-617b-11ea-9c2a-2ed63f2d66f9.png)

Hi @muxlowc

I'm down to just having an issue with my icons. Do Icons with <img> tags have to be in a ul/li? 

Thank you for your help!

**Comment by muxlowc** [comment]
@drew0036 no worries - I'll go in and give you the grade, as long as that's the last markbot issue

**Comment by drew0036** [comment]
Yes it is, thank you! It wouldn't look quite right without those quote marks.

**Comment by drew0036** [comment]
![Screen Shot 2020-03-09 at 1 58 58 PM](https://user-images.githubusercontent.com/55107709/76243105-3109a000-620e-11ea-9cb5-9d6c0612e712.png)
![Screen Shot 2020-03-09 at 1 59 10 PM](https://user-images.githubusercontent.com/55107709/76243107-31a23680-620e-11ea-976a-57715765a7aa.png)
