### ISSUE TITLE
Just My Type Rationale

### ISSUE THREAD

**Issue by drew0036** [drew0036/just-your-type#3]
**Brief:**
Code a beautiful typography layout for a quote.

**Original Quote:**
“I have heard there are troubles of more than one kind. Some come from ahead, and some come from behind. But I’ve bought a big bat. I’m all ready you see. Now my troubles are going to have troubles with me!”― Dr. Seuss

**Concept**
A brightly coloured and juvenile style that would suit the whimsy of Dr. Seuss’s children’s books.

**Elements**
The quote typeface is _Permanent Marker_. I selected this font because it looks handwritten in a child-like manner that is bold with its thick strokes to make it easy to read. I used the serif _Bitter_ for the citation line to be similar to the serif used in the body copy of Dr. Seuss’s books.

I used the golden scale ratio (1.618), so I can make the type large like the exaggeratedly large type in Dr. Seuss’ books.

I used the magenta, blue and yellow because they are bright, youthful, and have a vibrating appearance beside each other. I also used these colours because Dr. Suess’s work subverted expectations, so I wanted to stay far away from mundane colour combinations.   

My grid structure has grids within it so I could move the type from bottom and top to side to side. I also added icon units that sit behind other units. 

My greatest challenge was getting my quote mark icons to move around with the type as the viewport changes. The hardest part was getting the quote marks under the text; then, it was trial and error to get them to move up and down.

**Comment by drew0036** [comment]
@muxlowc

I'm sorry, I completely forgot to tag you in my rationale.
I hope all is well on your end! Stay safe!

**Comment by muxlowc** [comment]
@drew0036 thanks! good job! you can close this issue now

**Comment by drew0036** [comment]
Thank you!
